### ISSUE TITLE
Problem sichtbarkeit 

### ISSUE THREAD

**Issue by LucaBlue27** [yumi-modding/FS19_additionalFieldInfo#8]
Mein Problem ist es das ich irgendwie im MP bei die Sichtbarkeit des Mods deaktiviert haben muss, aber ich weiß nicht wie, da dieser Mod keinerlei Tastenkombinationen mit sich bringt. Ich dachte zuerst das es ein Bug des ods sei, aber bei meinen Mitspielern funktioniert der Mod, nur bei mir nicht. Es half auch nicht den Mod zu entfernen und später neu hinzu zu fügen. Ich bin allnämlich sehr ratlos und lasse ihn nur noch für meinen Mitspieler im Modordner. Habt ihr eine Idee wie man ihn wieder aktivieren kann??

**Comment by yumi-modding** [comment]
Hello
I must admit that I very rarely play in MP but I know the mod is working ok.
There is no key combination for this mods since it simply add information to the already existing panel. One thing could be that you have other mods adding text there (seasons for ex but I also use it) so info are hidden since we can only display 10 rows maximum.
Weird thing is other MP players can see it correctly.
Do you have any errors in the log file ?
While looking at the map, in the terrain buying mode, could you see their area or only their price? (only with last mod version)
